// =========== Name Database =============
var RandomName = [
	"Jacob", "William", "Ethan", "Daniel", "Logan", "God Of God",
	"Matthew", "Lucas", "Jackson", "David", "Samuel", "Dont Kill Me",
	"Luke", "Henry", "Andrew", "Nathan", "Huong", "Nhien", "Hacker",
	"Nhung", "Huynh", "Dat", "Dinh", "Hanh", "Ros", "Tay", "Japan Anti Virus",
	"Thanh", "Hue", "Nang", "Mua", "DeadClick", "Bao", "Tam", "FuckYou",
	"Dem", "Sang", "Cute", "Dude", "hateU", "Hope", "Car", "God", "Ninja",
	"Fake", "Alan", "Hoi", "Diem", "Master", "Be Friend or Die", "peace",
	"Yi", "Yasuo", "Irela", "Vi", "Lux", "Sion", "Doctor", "U r mine",
	"Jinx", "Jhin", "Roma", "Computer", "Fax", "Plane", "Sky", "Head",
	"Tree", "Lake", "Water", "Fire", "Snow", "Mountain", "Dog", "Hóng",
	"Cat", "Bird", "Snack", "Candy", "Huu", "Noah", "Mason", "Best Gamer",
	"Hoang", "Hien", "Linh", "Nam", "Tam", "Hau", "Foria", "JAVASCRIPT",
	"Hoa", "Thao", "Trang", "Thuy", "Huan", "Luong", "Test Game", "...",
	"Hao", "Thuan", "Nga", "Huy", "Hang", "An", "Anh", "Call me",
	"Thien", "Ngan", "<3", "Love", "Michael", "Seclo", "Play Alone",
	"Heo", "Julia", "Jame", "Thomson", "LOL", "Ris", "Soldier",
	"Tris", "Nhan", "Dang", "Dam", "Hi Five", "NAMASTE", "US", "BadBoys", "CoolDude", "JeherillaJanwar", 
	"Romeo", "Ishaan", "MAD_DOGI", "BOT", "Human", "Flower", "REAL", "Fighter", "cutt.ly/328069", "~", 
	"TimCOOK", "SteveJobs", "ElonMusk", "MonkeyPox", "Bandook", "Stockfish", "OGGY", ":)", "Cockroach", 
	"SushiMan", "SelfMade", "Snake", "Janwar", "Python", "Swift", "HTML", "Fuse", "Newt", "Newton", 
	"Einstein", "Bubbles", "Jeff", "POGO", "slick", "Zee", "Dost", "DhokhaDhadi", "Spam", "Cake", 
	"Rockit", "Boss", "tesla", "idk", "Splendid Lollipop", "Respectful Knight", 
	"Decrepit Detective", "Sizzling Sheriff", "WimpyKid", "Excited Ace", "Ancient Hamster",
	"Telescope", "LoveThisGame", "imagine..."
];
